# Generated by Django 5.2.13 on 2026-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='monto_total',
            new_name='importe_total',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='proveedor',
            new_name='nombre_proveedor',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='numero_factura',
            new_name='timbrado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='factura',
            name='ruc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('electronica', 'Factura Electrónica'), ('no_electronica', 'Factura No Electrónica')], default='no_electronica', max_length=20),
        ),
    ]
