# Generated by Django 5.2.13 on 2026-04-15 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_factura_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='carga_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='importe_impuesto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del impuesto incluido en la factura (ej: IVA)', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('sueldo', 'Sueldo'), ('freelance', 'Freelance'), ('venta', 'Venta'), ('alquiler', 'Alquiler'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
    ]
