# Generated by Django 5.2.13 on 2026-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_factura_carga_manual_factura_importe_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Número de factura (ej: 001-001-0000001)', max_length=50),
        ),
    ]
