# Generated by Django 5.2.13 on 2026-04-21 20:23

from django.conf import settings
from django.db import migrations, models


def eliminar_duplicados(apps, schema_editor):
    """Keep the newest record for each (usuario, ruc, timbrado, numero_factura) combo."""
    Factura = apps.get_model('facturas', 'Factura')
    seen = {}
    for f in Factura.objects.exclude(ruc='').exclude(timbrado='').exclude(numero_factura='').order_by('id'):
        key = (f.usuario_id, f.ruc, f.timbrado, f.numero_factura)
        if key in seen:
            seen[key].delete()
        seen[key] = f


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_google_sheet_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(eliminar_duplicados, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(('ruc', ''), _negated=True),
                    models.Q(('timbrado', ''), _negated=True),
                    models.Q(('numero_factura', ''), _negated=True),
                ),
                fields=('usuario', 'ruc', 'timbrado', 'numero_factura'),
                name='unique_factura_por_usuario_ruc_timbrado_numero',
            ),
        ),
    ]
