# Generated by Django 5.2.13 on 2026-04-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_unique_factura_ruc_timbrado_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-creado'], 'permissions': [('ver_todo', 'Puede ver transacciones de todos los usuarios')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
