# Generated by Django 5.2.13 on 2026-07-12 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_permiso_ver_todo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Contador que registró esta factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Contador que registró este ingreso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('usuario_normal', 'Usuario Normal'), ('contador', 'Contador')], default='usuario_normal', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Desactiva para bloquear el usuario')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ClienteContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_cliente', models.CharField(blank=True, help_text='RUC o ID fiscal del cliente', max_length=20)),
                ('nombre_razon_social', models.CharField(blank=True, help_text='Razón social registrada', max_length=255)),
                ('puede_crear_facturas', models.BooleanField(default=True)),
                ('puede_crear_ingresos', models.BooleanField(default=True)),
                ('puede_editar_transacciones', models.BooleanField(default=True)),
                ('puede_ver_reportes', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True, help_text='Desactiva para bloquear cliente sin eliminar')),
                ('fecha_bloqueo', models.DateTimeField(blank=True, help_text='Timestamp del bloqueo', null=True)),
                ('razon_bloqueo', models.TextField(blank=True, help_text='Razón por la que fue bloqueado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_contadores_vinculados', to=settings.AUTH_USER_MODEL)),
                ('contador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_clientes_vinculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente de Contador',
                'verbose_name_plural': 'Clientes de Contador',
                'ordering': ['-creado'],
                'constraints': [models.CheckConstraint(condition=models.Q(('contador', models.F('cliente')), _negated=True), name='contador_cliente_diferentes')],
                'unique_together': {('contador', 'cliente')},
            },
        ),
    ]
