# Generated by Django 5.2.13 on 2026-07-12 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_factura_registrado_por_ingreso_registrado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_usuario', models.CharField(blank=True, max_length=20)),
                ('nombre_razon_social', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('puede_crear_facturas', models.BooleanField(default=True)),
                ('puede_crear_ingresos', models.BooleanField(default=True)),
                ('puede_editar_transacciones', models.BooleanField(default=True)),
                ('puede_ver_reportes', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True, help_text='Desactiva para bloquear usuario sin eliminar')),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('razon_bloqueo', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('contador', models.ForeignKey(blank=True, help_text='Contador responsable de este usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_usuarios_normales', to=settings.AUTH_USER_MODEL)),
                ('usuario_normal', models.OneToOneField(help_text='Usuario normal que tiene este contador', on_delete=django.db.models.deletion.CASCADE, related_name='mi_contador_asoc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contador Usuario',
                'verbose_name_plural': 'Contadores Usuario',
                'ordering': ['-creado'],
            },
        ),
        migrations.DeleteModel(
            name='ClienteContador',
        ),
    ]
